### ISSUE TITLE
Create SchemaHSTORE

### ISSUE THREAD

**Issue by mahenzon** [AdCombo/combojsonapi#3]
We need to implement `SchemaHSTORE` like `SchemaJSONB`. Maybe `SchemaJSONB` has to be inherited from `SchemaHSTORE` because in python world it's just a one-level `dict`. So, smth like this:

```python
class SchemaHSTORE(Schema):
    class Meta:
        filtering = True


class SchemaJSONB(SchemaHSTORE):
    class Meta:
        filtering = True
```

OR create smth like base schema:

```python
from marshmallow import Schema


class JSONSchemaBase(Schema):
    class Meta:
        filtering = True


class SchemaHSTORE(JSONSchemaBase):
    """
    Doc for HSTORE
    """


class SchemaJSONB(JSONSchemaBase):
    """
    Doc for JSONB
    """
```

**Comment by Znbiz** [comment]
I do not think that this is an extremely necessary functionality. It is better to use JSONB
