### ISSUE TITLE
kwarg `many` in permission plugin

### ISSUE THREAD

**Issue by mahenzon** [AdCombo/combojsonapi#4]
Seems like the `many` kwarg is set to `True` in the permission plugin
https://github.com/AdCombo/combojsonapi/blob/7bbcd1f94c1de69e2402b03a3bbb8046b253b073/combojsonapi/permission/permission_plugin.py#L151

No matter if the passed `resource` is for List, or for Detail
https://github.com/AdCombo/combojsonapi/blob/7bbcd1f94c1de69e2402b03a3bbb8046b253b073/combojsonapi/permission/permission_plugin.py#L118

**Comment by Znbiz** [comment]
Thanks for fixing the bug
